[project]
name = "test-data-plotter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "streamlit>=1.50.0",
    "tk>=0.1.0",
]
